platform :ios, "11.0"
use_frameworks!
inhibit_all_warnings!

target 'ChatKeepcoding' do
    
  pod 'MessageKit', '~> 3.0.0'
  pod 'Firebase/Core'
  pod 'Firebase/Analytics'
  pod 'Firebase/Auth'
  pod 'Firebase/Database'
  pod 'FirebaseUI/Database'
  pod 'Firebase/Firestore'
  pod 'FirebaseStorage'
  pod 'Kingfisher'
  pod 'Firebase/Messaging'

end
